# Generated by Django 3.1.6 on 2021-02-13 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210212_0303'),
    ]

    operations = [
        migrations.RenameField('Post', 'autor', 'author'),
    ]
